name: "Prepare test environment with Tarantool CE"
description: "Prepares test environment with Tarantool CE"

inputs:
  tarantool-version:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '${{ env.GO_VERSION }}'

    - name: Setup Mage
      run: |
        git clone https://github.com/magefile/mage
        cd mage
        go run bootstrap.go
      shell: bash

    - name: Install build requirements
      run: |
        sudo apt -y update
        sudo apt -y install git gcc make cmake unzip zip
        sudo apt-get --allow-releaseinfo-change update
        sudo apt-get -y -f install \
        build-essential ninja-build \
        lua5.1 luarocks lcov \
        ruby-dev liblz4-dev  autoconf \
        automake \
        libtool
        sudo luarocks install luacheck 0.26.1
        sudo gem install coveralls-lcov
      shell: bash

    - name: Install docker requirements
      run: |
        sudo apt-get update && apt-get install -y ca-certificates curl gnupg lsb-release
        sudo mkdir -p /etc/apt/keyrings && curl -fsSL \
        https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io
      shell: bash

    - name: Install Tarantool
      uses: tarantool/setup-tarantool@v1
      with:
        tarantool-version: '${{ inputs.tarantool-version }}'

    - name: Stop and disable Taranool 1.10 example service
      if: matrix.tarantool-version == '1.10'
      run: |
        sudo systemctl stop tarantool@example || true
        sudo systemctl disable tarantool@example || true
        sudo rm -rf /lib/systemd/system/tarantool@.service
      shell: bash

    - name: Build tt
      run: mage build
      shell: bash
